#!/bin/bash

set -e
source "${REPO_ROOT}/ci/scripts/functions-ci.sh"
START_DIR="${PWD}"  # Differs for CI and manual execution

if [ -n "$FOCUS" ]; then
  echo "------------------------------------------------------------------"
  echo "FOCUS is set. Will only run tests matching '$FOCUS'"
  echo "------------------------------------------------------------------"
  ADDITIONAL_ARGS=("--focus" "$FOCUS")
fi

git_pull

if [ -f ".git/resource/changed_files" ]; then
  if skip_ci "ci/.ci-ignore" ".git/resource/changed_files"; then
    echo "SKIP TEST: Only .ci-ignored changes found."
    exit 0
  else
    echo "RUN TEST: There is at least one non-ignored change found."
  fi
fi

prepare_bosh

cd "acceptance-tests"

echo "----- Installing dependencies"
go mod download
go install github.com/onsi/ginkgo/v2/ginkgo

echo "----- Running tests"

export PATH=$PATH:$GOPATH/bin
ginkgo version

echo "------------------------------------------------------------------"
if [ -n "${FOCUS:-}" ]; then
  PARALLELISM="--nodes=1"
  echo "FOCUS is set, thus PARALLELISM is set to '$PARALLELISM'"
elif [ -n "${PARALLELISM:-}" ]; then
  PARALLELISM="--nodes=$PARALLELISM"
  echo "PARALLELISM is set. Will run ginkgo with '$PARALLELISM'"
else
  PARALLELISM="-p"
  echo "PARALLELISM is not set. Using default '$PARALLELISM'"
fi
echo "------------------------------------------------------------------"

echo "------------------------------------------------------------------"
if [ "${VERBOSITY:-}" = "vv" ]; then
  VERBOSITY_FLAG="-vv"
  echo "VERBOSITY is set to 'vv'. Will run ginkgo with '$VERBOSITY_FLAG'"
else
  VERBOSITY_FLAG="-v"
  echo "VERBOSITY is not set or unrecognised. Using default '$VERBOSITY_FLAG'"
fi
echo "------------------------------------------------------------------"

echo "------------------------------------------------------------------"
if [ -n "${FLAKE_ATTEMPTS:-}" ]; then
  echo "FLAKE_ATTEMPTS is set. Will run ginkgo with '--flake-attempts=$FLAKE_ATTEMPTS'"
else
  FLAKE_ATTEMPTS=5
  echo "FLAKE_ATTEMPTS is not set. Using default '$FLAKE_ATTEMPTS'"
fi
echo "------------------------------------------------------------------"

echo "------------------------------------------------------------------"
if [ -n "${SUITE_TIMEOUT:-}" ]; then
  echo "SUITE_TIMEOUT is set. Will run ginkgo with '--timeout=$SUITE_TIMEOUT'"
else
  SUITE_TIMEOUT="1h"
  echo "SUITE_TIMEOUT is not set. Using default '$SUITE_TIMEOUT'"
fi
echo "------------------------------------------------------------------"

echo "------------------------------------------------------------------"
if [ -n "${GRACE_PERIOD:-}" ]; then
  echo "GRACE_PERIOD is set. Will run ginkgo with '--grace-period=$GRACE_PERIOD'"
else
  GRACE_PERIOD="30s"
  echo "GRACE_PERIOD is not set. Using default '$GRACE_PERIOD'"
fi
echo "------------------------------------------------------------------"

ginkgo "$VERBOSITY_FLAG" "$PARALLELISM" -r --trace --show-node-events --randomize-all --flake-attempts "$FLAKE_ATTEMPTS" --timeout "$SUITE_TIMEOUT" --grace-period "$GRACE_PERIOD" "${ADDITIONAL_ARGS[@]}"

keep_running_info