---
name: haproxy

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm
  - name: bosh-dns
    properties:
      api:
        client:
          tls: ((/dns_api_client_tls))
        server:
          tls: ((/dns_api_server_tls))
      cache:
        enabled: true
      configure_systemd_resolved: true
      disable_recursors: true
      health:
        client:
          tls: ((/dns_healthcheck_client_tls))
        enabled: true
        server:
          tls: ((/dns_healthcheck_server_tls))
      override_nameserver: false
    release: bosh-dns

instance_groups:
- name: haproxy
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: haproxy
    release: haproxy
    properties:
      ha_proxy:
        backend_port: ((haproxy-backend-port))
        backend_servers: ((haproxy-backend-servers))

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

stemcells:
  - alias: default
    os: ubuntu-noble
    version: latest

releases:
- name: bpm
  version: 1.4.20
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.4.20
  sha1: 00223345c70d5629d35008e88c42bf4482bdf766
- name: haproxy
  version: 15.1.0+2.8.15
  url: https://github.com/cloudfoundry/haproxy-boshrelease/releases/download/v15.1.0+2.8.15/haproxy-15.1.0+2.8.15.tgz
  sha1: 87de2c7d011862eb5717654bf4a24aeec21ea41d
